version: '3.3'

services:
  db_service:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - "transmission"
    environment:
      - POSTGRES_USER : postgres
      - POSTGRES_PASSWORD : postgres
      - POSTGRES_DB : reverse_coding

  heimdall:
    depends_on:
      - db_service
    image: yashkumarverma/rc-heimdall
    ports:
      - "4000:80"
    restart: always
    networks: transmission
    environment:
      - PORT: 80
      - JUDGE_CALLBACK: http://localhost:4000/judge/callback
      - RUNNER_ENDPOINT_EXEC: https://webhook.site/1406fdc8-be02-4774-b694-7b9d0696e203 
      - RUNNER_ENDPOINT_SEED: https://webhook.site/1406fdc8-be02-4774-b694-7b9d0696e203
      - DATABASE_HOST: db_service
       
volumes:
  database:

networks:
  transmission: