api:
  route: API_ENDPOINT

runner:
  runEndpoint: RUNNER_ENDPOINT_EXEC
  seedEndpoint: RUNNER_ENDPOINT_SEED

server:
  port: PORT

database:
  host: DB_HOST
  username: DB_USERNAME
  password: DB_PASSWORD
  db_name: DB_NAME

judge:
  endpoint: JUDGE_ENDPOINT
  callback: JUDGE_CALLBACK

application:
  assignProblemToTeams: ASSIGN_PROBLEM_TO_TEAM