api:
  name: Heimdall
  description: Reverse Coding API Endpoint to handle question execution, interact with other micro-services, and provide API for internal operations.
  version: 1.0.0
  route: 'api'

database:
  type: 'postgres'
  port: 5432
  host: localhost
  username: 'postgres'
  password: 'postgres'
  db_name: 'reverse_coding'
  synchronize: true

server:
  port: 5000

runner:
  endpoint: http://localhost:8080/run

seeder:
  endpoint: https://rc-broadcaster.vercel.app/api/app.js