api:
  name: Heimdall
  description: Reverse Coding API Endpoint to handle question execution, interact with other micro-services, and provide API for internal operations.
  route: 'api'

database:
  type: 'postgres'
  port: 5432
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  db_name: 'reverse_coding'
  synchronize: true

server:
  port: 5000

runner:
  runEndpoint: http://localhost:8000/run
  seedEndpoint: http://localhost:8000/sync

seeder:
  endpoint: https://rc-broadcaster.vercel.app/api/app.js

judge:
  endpoint: http://40.76.50.156
  callback:  http://localhost:5000/judge/callback

code_response:
  in_queue: submission queued
  processing: submission is being evaluated
  accepted:  submission is accepted
  wrong: submission returned wrong answer
  tle: time limit exceeded
  compilation_error: code could not compile. check for syntax errors
  runtime_error: runtime error in code
  internal_error: internal server error
  code_error: undefined error encountered

application:
  assignProblemToTeams: false
