name: Deploy documentations

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: npm install, build
      run: |
        npm install
        npm run build
        npm i -g typedoc
    
    - name: Building documentation
      run: |
        typedoc
        npm run docs:compodoc

    - name: deploy compodoc
      uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'rc-heimdall.compodoc.ykv.surge.sh'
          project: 'documentation'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

    - name: deploy typedoc
      run: dswistowski/surge-sh-action@v1
        with:
          domain: 'rc-heimdall.typedoc.ykv.surge.sh'
          project: 'typedoc'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
